### ISSUE TITLE
Edit-Level : none

### ISSUE THREAD

**Issue by ppumkin** [krispo/json-tree#14]
I really like this plugin but for a particular use case I only need to view the JSON on a page, from debug data.

**Comment by krispo** [comment]
From the box we can use either `low` or `high` edit levels, but it's editable.. However, you can play with custom template and try to change it as you need. For example, just remove editable part (line 24):
```js
'<input ng-if="childs[key].type() === \'boolean\'" type="checkbox" ng-model="json[key]"/>' +
'<input  ... />' +
'<textarea  ... ></textarea>' +
'<input  ... />' +
```
and add a static one instead: 
```js
'<span ng-if="childs[key].type() === \'number\'">{{::json[key]}}</span>' +
'<span ng-if="childs[key].type() !== \'number\'">"{{::json[key]}}"</span>' +
```
