### ISSUE TITLE
Limit watchers to expanded branches

### ISSUE THREAD

**Issue by pdemilly** [krispo/json-tree#16]
as or 1.3 if you have a json that is fairly large, the directive creates many watchers (for example for an array or array of 30 x 30 around 15000 watchers are created). A very welcome enhancement would be to only create the editors when a branch is expanded for the immediate descendants leaves. For a branch you would only have the ng-click watcher.

 To compute the number of watchers I used ng-stats  . You can find it here: [https://github.com/kentcdodds/ng-stats](https://github.com/kentcdodds/ng-stats)

**Comment by pdemilly** [comment]
See pull request https://github.com/krispo/json-tree/pull/17

**Comment by krispo** [comment]
There was a reason why I left `ng-hide` instead of `ng-if`.. not sure.. 
But I'll add your changes, thanks!
