### ISSUE TITLE
not compatible with ng-strict mode

### ISSUE THREAD

**Issue by girafi** [krispo/json-tree#20]
When embedding this cool json-tree into an angular app that runs in "ng-strict-mode", json-tree breaks the app, because it is not fully compliant with the ng-strict mode.

The following two Lines need to be changed:

- https://github.com/krispo/json-tree/blob/master/json-tree.js#L71 -> ['$scope, function ($scope) ...

- https://github.com/krispo/json-tree/blob/master/json-tree.js#L383 -> ['$document, function ($document)

Then it works again :)

Thanks in advance

**Comment by krispo** [comment]
Thanks! It's fixed.
